using System;
using System.Collections.Generic;
using UnityEngine;

namespace FairyGUI;

[ExecuteInEditMode]
[AddComponentMenu("FairyGUI/UI Panel")]
public class UIPanel : MonoBehaviour, EMRenderTarget
{
	public string packageName;

	public string componentName;

	public FitScreen fitScreen;

	public int sortingOrder;

	[SerializeField]
	private string packagePath;

	[SerializeField]
	private RenderMode renderMode;

	[SerializeField]
	private Camera renderCamera;

	[SerializeField]
	private Vector3 position;

	[SerializeField]
	private Vector3 scale = new Vector3(1f, 1f, 1f);

	[SerializeField]
	private Vector3 rotation = new Vector3(0f, 0f, 0f);

	[SerializeField]
	private bool fairyBatching;

	[SerializeField]
	private bool touchDisabled;

	[SerializeField]
	private Vector2 cachedUISize;

	[SerializeField]
	private HitTestMode hitTestMode;

	[SerializeField]
	private bool setNativeChildrenOrder;

	[NonSerialized]
	private int screenSizeVer;

	[NonSerialized]
	private Rect uiBounds;

	private GComponent _ui;

	[NonSerialized]
	private bool _created;

	private List<Renderer> _renders;

	public Container container { get; private set; }

	public GComponent ui
	{
		get
		{
			if (!_created && Application.isPlaying)
			{
				if (!string.IsNullOrEmpty(packagePath) && UIPackage.GetByName(packageName) == null)
				{
					UIPackage.AddPackage(packagePath);
				}
				CreateUI_PlayMode();
			}
			return _ui;
		}
	}

	public int EM_sortingOrder => sortingOrder;

	private void OnEnable()
	{
		if (Application.isPlaying)
		{
			if (container == null)
			{
				CreateContainer();
				if (!string.IsNullOrEmpty(packagePath) && UIPackage.GetByName(packageName) == null)
				{
					UIPackage.AddPackage(packagePath);
				}
			}
			return;
		}
		if (container != null)
		{
			OnDestroy();
		}
		EMRenderSupport.Add(this);
		screenSizeVer = 0;
		uiBounds.position = position;
		uiBounds.size = cachedUISize;
		if (uiBounds.size == Vector2.zero)
		{
			uiBounds.size = new Vector2(30f, 30f);
		}
	}

	private void OnDisable()
	{
		if (!Application.isPlaying)
		{
			EMRenderSupport.Remove(this);
		}
	}

	private void Start()
	{
		if (!_created && Application.isPlaying)
		{
			CreateUI_PlayMode();
		}
	}

	private void Update()
	{
		if (screenSizeVer != StageCamera.screenSizeVer)
		{
			HandleScreenSizeChanged();
		}
	}

	private void OnDestroy()
	{
		if (container != null)
		{
			if (!Application.isPlaying)
			{
				EMRenderSupport.Remove(this);
			}
			if (_ui != null)
			{
				_ui.Dispose();
				_ui = null;
			}
			container.Dispose();
			container = null;
		}
		_renders = null;
	}

	private void CreateContainer()
	{
		//IL_005e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0063: Unknown result type (might be due to invalid IL or missing references)
		if (!Application.isPlaying)
		{
			Transform transform = base.transform;
			for (int num = transform.childCount; num > 0; num--)
			{
				GameObject gameObject = transform.GetChild(num - 1).gameObject;
				if (gameObject.name == "UI(AutoGenerated)")
				{
					UnityEngine.Object.DestroyImmediate(gameObject);
				}
			}
		}
		container = new Container(base.gameObject);
		container.renderMode = renderMode;
		container.renderCamera = renderCamera;
		container.touchable = !touchDisabled;
		container._panelOrder = sortingOrder;
		container.fairyBatching = fairyBatching;
		if (!Application.isPlaying)
		{
			return;
		}
		SetSortingOrder(sortingOrder, apply: true);
		if (hitTestMode == HitTestMode.Raycast)
		{
			ColliderHitTest colliderHitTest = new ColliderHitTest();
			colliderHitTest.collider = (Collider)(object)base.gameObject.AddComponent<BoxCollider>();
			container.hitArea = colliderHitTest;
		}
		if (!setNativeChildrenOrder)
		{
			return;
		}
		CacheNativeChildrenRenderers();
		container.onUpdate += delegate
		{
			int count = _renders.Count;
			int num2 = UpdateContext.current.renderingOrder++;
			for (int i = 0; i < count; i++)
			{
				if (_renders[i] != null)
				{
					_renders[i].sortingOrder = num2;
				}
			}
		};
	}

	public void CreateUI()
	{
		if (_ui != null)
		{
			_ui.Dispose();
			_ui = null;
		}
		CreateUI_PlayMode();
	}

	public void SetSortingOrder(int value, bool apply)
	{
		sortingOrder = value;
		container._panelOrder = value;
		if (apply)
		{
			Stage.inst.ApplyPanelOrder(container);
		}
	}

	public void SetHitTestMode(HitTestMode value)
	{
		if (hitTestMode == value)
		{
			return;
		}
		hitTestMode = value;
		BoxCollider val = base.gameObject.GetComponent<BoxCollider>();
		if (hitTestMode == HitTestMode.Raycast)
		{
			if ((UnityEngine.Object)(object)val == null)
			{
				val = base.gameObject.AddComponent<BoxCollider>();
			}
			ColliderHitTest colliderHitTest = new ColliderHitTest();
			colliderHitTest.collider = (Collider)(object)val;
			container.hitArea = colliderHitTest;
			if (_ui != null)
			{
				UpdateHitArea();
			}
		}
		else
		{
			container.hitArea = null;
			if ((UnityEngine.Object)(object)val != null)
			{
				UnityEngine.Object.Destroy((UnityEngine.Object)(object)val);
			}
		}
	}

	public void CacheNativeChildrenRenderers()
	{
		if (_renders == null)
		{
			_renders = new List<Renderer>();
		}
		else
		{
			_renders.Clear();
		}
		Transform cachedTransform = container.cachedTransform;
		int childCount = cachedTransform.childCount;
		for (int i = 0; i < childCount; i++)
		{
			GameObject gameObject = cachedTransform.GetChild(i).gameObject;
			if (gameObject.name != "GComponent")
			{
				_renders.AddRange(gameObject.GetComponentsInChildren<Renderer>(includeInactive: true));
			}
		}
		childCount = _renders.Count;
		for (int j = 0; j < childCount; j++)
		{
			Renderer renderer = _renders[j];
			if ((renderer is SkinnedMeshRenderer || renderer is MeshRenderer) && renderer.sharedMaterial != null)
			{
				renderer.sharedMaterial.renderQueue = 3000;
			}
		}
	}

	private void CreateUI_PlayMode()
	{
		_created = true;
		if (string.IsNullOrEmpty(packageName) || string.IsNullOrEmpty(componentName))
		{
			return;
		}
		_ui = (GComponent)UIPackage.CreateObject(packageName, componentName);
		if (_ui != null)
		{
			_ui.position = position;
			if (scale.x != 0f && scale.y != 0f)
			{
				_ui.scale = scale;
			}
			_ui.rotationX = rotation.x;
			_ui.rotationY = rotation.y;
			_ui.rotation = rotation.z;
			if (container.hitArea != null)
			{
				UpdateHitArea();
				_ui.onSizeChanged.Add(UpdateHitArea);
				_ui.onPositionChanged.Add(UpdateHitArea);
			}
			container.AddChildAt(_ui.displayObject, 0);
			HandleScreenSizeChanged();
		}
		else
		{
			Debug.LogError("Create " + packageName + "/" + componentName + " failed!");
		}
	}

	private void UpdateHitArea()
	{
		//IL_001a: Unknown result type (might be due to invalid IL or missing references)
		//IL_006a: Unknown result type (might be due to invalid IL or missing references)
		if (container.hitArea is ColliderHitTest colliderHitTest)
		{
			((BoxCollider)colliderHitTest.collider).center = new Vector3(_ui.xMin + _ui.width / 2f, 0f - _ui.yMin - _ui.height / 2f);
			((BoxCollider)colliderHitTest.collider).size = _ui.size;
		}
	}

	private void CreateUI_EditMode()
	{
		if (!EMRenderSupport.packageListReady || UIPackage.GetByName(packageName) == null)
		{
			return;
		}
		DisplayObject.hideFlags = HideFlags.DontSaveInEditor;
		GObject gObject = UIPackage.CreateObject(packageName, componentName);
		if (gObject != null && !(gObject is GComponent))
		{
			gObject.Dispose();
			Debug.LogWarning("Not a GComponnet: " + packageName + "/" + componentName);
			return;
		}
		_ui = (GComponent)gObject;
		if (_ui != null)
		{
			_ui.displayObject.gameObject.hideFlags |= HideFlags.HideInHierarchy;
			_ui.gameObjectName = "UI(AutoGenerated)";
			_ui.position = position;
			if (scale.x != 0f && scale.y != 0f)
			{
				_ui.scale = scale;
			}
			_ui.rotationX = rotation.x;
			_ui.rotationY = rotation.y;
			_ui.rotation = rotation.z;
			container.AddChildAt(_ui.displayObject, 0);
			cachedUISize = _ui.size;
			uiBounds.size = cachedUISize;
			HandleScreenSizeChanged();
		}
	}

	private void HandleScreenSizeChanged()
	{
		//IL_007c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0082: Invalid comparison between Unknown and I4
		if (!Application.isPlaying)
		{
			DisplayObject.hideFlags = HideFlags.DontSaveInEditor;
		}
		screenSizeVer = StageCamera.screenSizeVer;
		int num = Screen.width;
		int num2 = Screen.height;
		if (container != null)
		{
			Camera camera = container.GetRenderCamera();
			if (camera.targetDisplay != 0 && camera.targetDisplay < Display.displays.Length)
			{
				num = Display.displays[camera.targetDisplay].renderingWidth;
				num2 = Display.displays[camera.targetDisplay].renderingHeight;
			}
			if ((int)container.renderMode != 2)
			{
				StageCamera component = camera.GetComponent<StageCamera>();
				if (component == null)
				{
					component = StageCamera.main.GetComponent<StageCamera>();
				}
				container.scale = new Vector2(component.unitsPerPixel * UIContentScaler.scaleFactor, component.unitsPerPixel * UIContentScaler.scaleFactor);
			}
		}
		num = Mathf.CeilToInt((float)num / UIContentScaler.scaleFactor);
		num2 = Mathf.CeilToInt((float)num2 / UIContentScaler.scaleFactor);
		if (_ui != null)
		{
			switch (fitScreen)
			{
			case FitScreen.FitSize:
				_ui.SetSize(num, num2);
				_ui.SetXY(0f, 0f, topLeftValue: true);
				break;
			case FitScreen.FitWidthAndSetMiddle:
				_ui.SetSize(num, _ui.sourceHeight);
				_ui.SetXY(0f, (num2 - _ui.sourceHeight) / 2, topLeftValue: true);
				break;
			case FitScreen.FitHeightAndSetCenter:
				_ui.SetSize(_ui.sourceWidth, num2);
				_ui.SetXY((num - _ui.sourceWidth) / 2, 0f, topLeftValue: true);
				break;
			}
			UpdateHitArea();
		}
		else
		{
			switch (fitScreen)
			{
			case FitScreen.FitSize:
				uiBounds.position = new Vector2(0f, 0f);
				uiBounds.size = new Vector2(num, num2);
				break;
			case FitScreen.FitWidthAndSetMiddle:
				uiBounds.position = new Vector2(0f, (int)(((float)num2 - cachedUISize.y) / 2f));
				uiBounds.size = new Vector2(num, cachedUISize.y);
				break;
			case FitScreen.FitHeightAndSetCenter:
				uiBounds.position = new Vector2((int)(((float)num - cachedUISize.x) / 2f), 0f);
				uiBounds.size = new Vector2(cachedUISize.x, num2);
				break;
			}
		}
	}

	private void OnUpdateSource(object[] data)
	{
		if (!Application.isPlaying)
		{
			packageName = (string)data[0];
			packagePath = (string)data[1];
			componentName = (string)data[2];
			if ((bool)data[3] && container != null && _ui != null)
			{
				_ui.Dispose();
				_ui = null;
			}
		}
	}

	public void ApplyModifiedProperties(bool sortingOrderChanged, bool fitScreenChanged)
	{
		//IL_000f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0014: Unknown result type (might be due to invalid IL or missing references)
		if (container != null)
		{
			container.renderMode = renderMode;
			container.renderCamera = renderCamera;
			if (sortingOrderChanged)
			{
				container._panelOrder = sortingOrder;
				if (Application.isPlaying)
				{
					SetSortingOrder(sortingOrder, apply: true);
				}
				else
				{
					EMRenderSupport.orderChanged = true;
				}
			}
			container.fairyBatching = fairyBatching;
		}
		if (_ui != null)
		{
			if (fitScreen == FitScreen.None)
			{
				_ui.position = position;
			}
			if (scale.x != 0f && scale.y != 0f)
			{
				_ui.scale = scale;
			}
			_ui.rotationX = rotation.x;
			_ui.rotationY = rotation.y;
			_ui.rotation = rotation.z;
		}
		if (fitScreen == FitScreen.None)
		{
			uiBounds.position = position;
		}
		screenSizeVer = 0;
		if (fitScreenChanged && fitScreen == FitScreen.None)
		{
			if (_ui != null)
			{
				_ui.SetSize(_ui.sourceWidth, _ui.sourceHeight);
			}
			uiBounds.size = cachedUISize;
		}
	}

	public void MoveUI(Vector3 delta)
	{
		if (fitScreen == FitScreen.None)
		{
			position += delta;
			if (_ui != null)
			{
				_ui.position = position;
			}
			uiBounds.position = position;
		}
	}

	public Vector3 GetUIWorldPosition()
	{
		if (_ui != null)
		{
			return _ui.displayObject.cachedTransform.position;
		}
		return container.cachedTransform.TransformPoint(uiBounds.position);
	}

	private void OnDrawGizmos()
	{
		if (!Application.isPlaying && container != null)
		{
			Vector3 center;
			Vector3 size;
			if (_ui != null)
			{
				Gizmos.matrix = _ui.displayObject.cachedTransform.localToWorldMatrix;
				center = new Vector3(_ui.width / 2f, (0f - _ui.height) / 2f, 0f);
				size = new Vector3(_ui.width, _ui.height, 0f);
			}
			else
			{
				Gizmos.matrix = container.cachedTransform.localToWorldMatrix;
				center = new Vector3(uiBounds.x + uiBounds.width / 2f, 0f - uiBounds.y - uiBounds.height / 2f, 0f);
				size = new Vector3(uiBounds.width, uiBounds.height, 0f);
			}
			Gizmos.color = new Color(0f, 0f, 0f, 0f);
			Gizmos.DrawCube(center, size);
			Gizmos.color = Color.white;
			Gizmos.DrawWireCube(center, size);
		}
	}

	public void EM_BeforeUpdate()
	{
		if (container == null)
		{
			CreateContainer();
		}
		if (packageName != null && componentName != null && _ui == null)
		{
			CreateUI_EditMode();
		}
		if (screenSizeVer != StageCamera.screenSizeVer)
		{
			HandleScreenSizeChanged();
		}
	}

	public void EM_Update(UpdateContext context)
	{
		DisplayObject.hideFlags = HideFlags.DontSaveInEditor;
		container.Update(context);
		if (!setNativeChildrenOrder)
		{
			return;
		}
		CacheNativeChildrenRenderers();
		int count = _renders.Count;
		int num = context.renderingOrder++;
		for (int i = 0; i < count; i++)
		{
			Renderer renderer = _renders[i];
			if (renderer != null)
			{
				renderer.sortingOrder = num;
			}
		}
	}

	public void EM_Reload()
	{
		if (_ui != null)
		{
			_ui.Dispose();
			_ui = null;
		}
	}
}
