package trace

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

const (
	CaptureStatusRecording  = "recording"
	CaptureStatusStopping   = "stopping"
	CaptureStatusStopped    = "stopped"
	CaptureStatusIncomplete = "incomplete"

	defaultCaptureQueueEvents = 256
	defaultCaptureQueueBytes  = 32 << 20
	maxCapturePageBytes       = 32 << 20
	maxCaptureMetadataLine    = 64 << 10
	// The default limits cumulative JSONL event data in the capture directory.
	// It intentionally does not count metadata sidecars or filesystem overhead.
	defaultCaptureTotalBytes = 1 << 30
	maxCapturePageSize       = 1000
)

var (
	ErrCaptureNotFound     = errors.New("capture session not found")
	ErrCaptureActive       = errors.New("a capture session is already active")
	ErrCaptureClosed       = errors.New("capture store is closed")
	ErrCaptureStorageFull  = errors.New("capture storage quota exhausted")
	ErrInvalidCapture      = errors.New("invalid capture session id")
	ErrCaptureLineTooLarge = errors.New("capture event line exceeds the read limit")
)

// CaptureStorageUsage is a point-in-time view of the capture data quota.
// UsedBytes counts capture data file bytes on disk, including any unrecoverable
// partial bytes; ReservedBytes counts accepted event bytes queued or currently
// being written. Metadata sidecars and filesystem overhead are not included.
type CaptureStorageUsage struct {
	UsedBytes      int64 `json:"usedBytes"`
	ReservedBytes  int64 `json:"reservedBytes"`
	MaxBytes       int64 `json:"maxBytes"`
	AvailableBytes int64 `json:"availableBytes"`
}

// CaptureMetadata describes one persisted capture session. The session ID is
// generated by CaptureStore and is also the only value used in its filenames.
type CaptureMetadata struct {
	ID               string     `json:"id"`
	Status           string     `json:"status"`
	StartedAt        time.Time  `json:"startedAt"`
	EndedAt          *time.Time `json:"endedAt,omitempty"`
	MaxBytes         int64      `json:"maxBytes"`
	Bytes            int64      `json:"bytes"`
	EventCount       int64      `json:"eventCount"`
	IncompleteReason string     `json:"incompleteReason,omitempty"`
}

// CaptureStore persists events as JSONL. It permits one accepting session at a
// time; events already queued for a stopped session are drained by its writer.
type CaptureStore struct {
	mu              sync.RWMutex
	dir             string
	lockFile        *os.File
	maxSessionBytes int64
	maxTotalBytes   int64
	usedBytes       int64
	reservedBytes   int64
	queueEvents     int
	queueBytes      int64
	sessions        map[string]*captureSession
	activeID        string
	creating        bool
	closed          bool
}

// CaptureProducer pins a recording session for one HTTP transaction, TCP
// frame read, or socket write. A manual stop waits for producers that started
// before the stop, then drains their events before returning.
type CaptureProducer struct {
	store           *CaptureStore
	session         *captureSession
	id              string
	mu              sync.Mutex
	closed          bool
	omissionReasons string
	once            sync.Once
}

type captureSession struct {
	store *CaptureStore

	mu            sync.Mutex
	metadataMu    sync.Mutex
	meta          CaptureMetadata
	file          *os.File
	queue         chan []byte
	stop          chan struct{}
	done          chan struct{}
	accepting     bool
	producers     int
	producersDone chan struct{}
	stopStatus    string
	stopReason    string
	queuedBytes   int64
}

// NewCaptureStore opens a directory for capture files and recovers sessions
// left recording by a previous process. maxSessionBytes must be positive.
// maxTotalBytes optionally limits persisted plus queued/in-flight JSONL event
// bytes across the directory; when omitted it defaults to 1 GiB. This quota
// excludes metadata sidecars and filesystem overhead. Recovered bytes count
// against the quota, so an existing directory may start over quota and reject
// new sessions until data is removed externally.
func NewCaptureStore(dir string, maxSessionBytes int64, maxTotalBytes ...int64) (*CaptureStore, error) {
	if strings.TrimSpace(dir) == "" {
		return nil, errors.New("capture directory is required")
	}
	if maxSessionBytes <= 0 {
		return nil, errors.New("capture session byte limit must be positive")
	}
	if len(maxTotalBytes) > 1 {
		return nil, errors.New("at most one capture total byte limit may be provided")
	}
	totalLimit := int64(defaultCaptureTotalBytes)
	if len(maxTotalBytes) == 1 {
		totalLimit = maxTotalBytes[0]
	}
	if totalLimit <= 0 {
		return nil, errors.New("capture total byte limit must be positive")
	}
	absDir, err := filepath.Abs(filepath.Clean(dir))
	if err != nil {
		return nil, fmt.Errorf("resolve capture directory: %w", err)
	}
	if err = os.MkdirAll(absDir, 0700); err != nil {
		return nil, fmt.Errorf("create capture directory: %w", err)
	}
	dirInfo, err := os.Lstat(absDir)
	if err != nil {
		return nil, fmt.Errorf("inspect capture directory: %w", err)
	}
	if !dirInfo.IsDir() || dirInfo.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("capture directory must be a real directory, not a symlink")
	}
	// Capture files may contain credentials and private messages. Keep the
	// directory private where the operating system supports Unix permissions.
	if err = os.Chmod(absDir, 0700); err != nil {
		return nil, fmt.Errorf("restrict capture directory permissions: %w", err)
	}
	lockFile, err := lockCaptureDirectory(absDir)
	if err != nil {
		return nil, err
	}

	store := &CaptureStore{
		dir:             absDir,
		lockFile:        lockFile,
		maxSessionBytes: maxSessionBytes,
		maxTotalBytes:   totalLimit,
		queueEvents:     defaultCaptureQueueEvents,
		queueBytes:      defaultCaptureQueueBytes,
		sessions:        make(map[string]*captureSession),
	}
	if err = store.recoverSessions(); err != nil {
		_ = unlockCaptureDirectory(lockFile)
		return nil, err
	}
	return store, nil
}

// CreateSession creates a unique JSONL file and starts its asynchronous writer.
func (s *CaptureStore) CreateSession() (CaptureMetadata, error) {
	if s == nil {
		return CaptureMetadata{}, errors.New("capture store is nil")
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return CaptureMetadata{}, ErrCaptureClosed
	}
	if s.creating {
		s.mu.Unlock()
		return CaptureMetadata{}, ErrCaptureActive
	}
	if s.activeID != "" {
		if active := s.sessions[s.activeID]; active != nil && active.isAccepting() {
			s.mu.Unlock()
			return CaptureMetadata{}, ErrCaptureActive
		}
		s.activeID = ""
	}
	if s.availableLocked() == 0 {
		s.mu.Unlock()
		return CaptureMetadata{}, ErrCaptureStorageFull
	}
	s.creating = true
	s.mu.Unlock()
	installed := false
	defer func() {
		if !installed {
			s.mu.Lock()
			s.creating = false
			s.mu.Unlock()
		}
	}()

	for attempts := 0; attempts < 8; attempts++ {
		id, err := newCaptureID()
		if err != nil {
			return CaptureMetadata{}, fmt.Errorf("generate capture session id: %w", err)
		}
		if _, exists := s.sessions[id]; exists {
			continue
		}
		dataPath, metaPath, err := s.paths(id)
		if err != nil {
			return CaptureMetadata{}, err
		}
		dataFile, err := os.OpenFile(dataPath, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
		if errors.Is(err, os.ErrExist) {
			continue
		}
		if err != nil {
			return CaptureMetadata{}, fmt.Errorf("create capture data file: %w", err)
		}
		meta := CaptureMetadata{
			ID:        id,
			Status:    CaptureStatusRecording,
			StartedAt: time.Now().UTC(),
			MaxBytes:  s.maxSessionBytes,
		}
		if err = createMetadataFile(metaPath, meta); err != nil {
			_ = dataFile.Close()
			_ = os.Remove(dataPath)
			return CaptureMetadata{}, fmt.Errorf("create capture metadata: %w", err)
		}
		cs := &captureSession{
			store:         s,
			meta:          meta,
			file:          dataFile,
			queue:         make(chan []byte, s.queueEvents),
			stop:          make(chan struct{}, 1),
			done:          make(chan struct{}),
			accepting:     true,
			producersDone: closedSignal(),
		}
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			_ = dataFile.Close()
			_ = os.Remove(dataPath)
			_ = os.Remove(metaPath)
			return CaptureMetadata{}, ErrCaptureClosed
		}
		// Recheck because a caller may have reserved bytes for a prior session
		// while this file was being created.
		if s.availableLocked() == 0 {
			s.mu.Unlock()
			_ = dataFile.Close()
			_ = os.Remove(dataPath)
			_ = os.Remove(metaPath)
			return CaptureMetadata{}, ErrCaptureStorageFull
		}
		s.sessions[id] = cs
		s.activeID = id
		s.creating = false
		s.mu.Unlock()
		installed = true
		go cs.run()
		return cloneCaptureMetadata(meta), nil
	}
	return CaptureMetadata{}, errors.New("could not allocate unique capture session id")
}

// StopSession stops accepting events and waits for queued events to be written.
// A session already stopped or marked incomplete is returned unchanged.
func (s *CaptureStore) StopSession(id string) (CaptureMetadata, error) {
	cs, err := s.session(id)
	if err != nil {
		return CaptureMetadata{}, err
	}
	if cs.requestStop(CaptureStatusStopped, "") {
		s.deactivate(id)
	}
	<-cs.done
	return cs.snapshot(), nil
}

// ActiveSession returns the currently accepting session, if one exists.
func (s *CaptureStore) ActiveSession() (CaptureMetadata, bool) {
	if s == nil {
		return CaptureMetadata{}, false
	}
	s.mu.RLock()
	id := s.activeID
	cs := s.sessions[id]
	s.mu.RUnlock()
	if id == "" || cs == nil || !cs.isAccepting() {
		return CaptureMetadata{}, false
	}
	return cs.snapshot(), true
}

// StorageUsage returns a stable, point-in-time quota snapshot. ReservedBytes
// includes accepted events queued for a writer and a line being written.
func (s *CaptureStore) StorageUsage() CaptureStorageUsage {
	if s == nil {
		return CaptureStorageUsage{}
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return CaptureStorageUsage{
		UsedBytes:      s.usedBytes,
		ReservedBytes:  s.reservedBytes,
		MaxBytes:       s.maxTotalBytes,
		AvailableBytes: s.availableLocked(),
	}
}

// Append adds an event to the active session without waiting for disk I/O. It
// returns false if there is no accepting session or the bounded queue rejects
// the event. Rejection marks that session incomplete and stops it.
func (s *CaptureStore) Append(event Event) bool {
	if s == nil {
		return false
	}
	s.mu.RLock()
	id := s.activeID
	cs := s.sessions[id]
	closed := s.closed
	s.mu.RUnlock()
	if closed || id == "" || cs == nil {
		return false
	}
	return s.AppendToSession(id, event)
}

// MarkActiveIncomplete terminates the current capture when an event cannot be
// retained because the bounded producer budget is exhausted.
func (s *CaptureStore) MarkActiveIncomplete(reason string) bool {
	if s == nil {
		return false
	}
	s.mu.RLock()
	id := s.activeID
	s.mu.RUnlock()
	return s.MarkSessionIncomplete(id, reason)
}

// MarkSessionIncomplete terminates one accepting session without affecting a
// newer session that may have started while a producer was working.
func (s *CaptureStore) MarkSessionIncomplete(id, reason string) bool {
	cs, err := s.session(id)
	if err != nil {
		return false
	}
	cs.fail(reason)
	return true
}

// AppendToSession is the session-specific form of Append. JSON encoding is
// performed before the nonblocking queue operation so queued events are
// immutable and the writer never observes caller mutations to Event slices.
func (s *CaptureStore) AppendToSession(id string, event Event) bool {
	return s.appendToSession(id, event, nil)
}

// BeginProducer pins the requested active session until the returned producer
// is closed. Use it when the session ID is already known, such as an HTTP
// transaction that began after the request entered the handler.
func (s *CaptureStore) BeginProducer(id string) (*CaptureProducer, bool) {
	cs, err := s.session(id)
	if err != nil {
		return nil, false
	}
	return s.beginProducer(id, cs)
}

// BeginActiveProducer atomically pins the currently accepting session. Call
// it when a captured operation starts, rather than before a potentially idle
// socket read, so a capture can begin while connections are already open.
func (s *CaptureStore) BeginActiveProducer() (*CaptureProducer, bool) {
	if s == nil {
		return nil, false
	}
	s.mu.RLock()
	id := s.activeID
	cs := s.sessions[id]
	closed := s.closed
	s.mu.RUnlock()
	if closed || id == "" || cs == nil {
		return nil, false
	}
	return s.beginProducer(id, cs)
}

func (s *CaptureStore) beginProducer(id string, cs *captureSession) (*CaptureProducer, bool) {
	cs.mu.Lock()
	defer cs.mu.Unlock()
	if !cs.accepting {
		return nil, false
	}
	if cs.producers == 0 {
		cs.producersDone = make(chan struct{})
	}
	cs.producers++
	return &CaptureProducer{store: s, session: cs, id: id}, true
}

// MarkIncomplete records an event-retention failure for this producer. The
// session transitions when the producer closes, preserving already accepted
// events for the writer to drain.
func (p *CaptureProducer) MarkIncomplete(reason string) {
	if p == nil || strings.TrimSpace(reason) == "" {
		return
	}
	p.mu.Lock()
	if !p.closed {
		p.omissionReasons = appendReason(p.omissionReasons, reason)
	}
	p.mu.Unlock()
}

// Append adds an immutable event to the producer's pinned session.
func (p *CaptureProducer) Append(event Event) bool {
	if p == nil {
		return false
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.closed {
		return false
	}
	if !p.store.appendToSession(p.id, event, p) {
		return false
	}
	if event.RawFrameOmitted != "" {
		p.omissionReasons = appendReason(p.omissionReasons, "raw_frame_omitted")
	}
	if event.RawBodyOmitted != "" {
		p.omissionReasons = appendReason(p.omissionReasons, "raw_body_omitted")
	}
	return true
}

// Close releases the session pin. It is safe to call more than once.
func (p *CaptureProducer) Close() {
	if p == nil {
		return
	}
	p.once.Do(func() {
		p.mu.Lock()
		p.closed = true
		reason := p.omissionReasons
		p.mu.Unlock()
		if reason != "" {
			p.session.markIncompleteBeforeDrain(reason)
		}
		p.session.mu.Lock()
		p.session.producers--
		if p.session.producers == 0 {
			close(p.session.producersDone)
		}
		p.session.mu.Unlock()
	})
}

func (s *CaptureStore) appendToSession(id string, event Event, producer *CaptureProducer) bool {
	cs, err := s.session(id)
	if err != nil {
		return false
	}
	leased := producer != nil && producer.session == cs
	if !cs.canAppend(leased) {
		if !leased {
			cs.noteLateEvent()
		}
		return false
	}
	line, err := json.Marshal(event)
	if err != nil {
		if leased {
			cs.markIncompleteBeforeDrain("event_encode_failed")
		} else {
			cs.fail("event_encode_failed")
		}
		return false
	}
	line = append(line, '\n')
	lineBytes := int64(len(line))
	if err = s.reserveBytes(lineBytes, leased); err != nil {
		if errors.Is(err, ErrCaptureStorageFull) {
			if leased {
				cs.markIncompleteBeforeDrain("storage_limit_reached")
			} else {
				cs.fail("storage_limit_reached")
			}
		}
		return false
	}

	cs.mu.Lock()
	if !cs.canAppendLocked(leased) {
		cs.mu.Unlock()
		s.releaseReservedBytes(lineBytes)
		if !leased {
			cs.noteLateEvent()
		}
		return false
	}
	if lineBytes > cs.meta.MaxBytes || cs.meta.Bytes+cs.queuedBytes+lineBytes > cs.meta.MaxBytes {
		cs.stopLocked(CaptureStatusIncomplete, "max_bytes_reached")
		cs.mu.Unlock()
		s.releaseReservedBytes(lineBytes)
		cs.signalStop()
		s.deactivate(id)
		return false
	}
	if cs.queuedBytes+lineBytes > s.queueBytes {
		cs.stopLocked(CaptureStatusIncomplete, "queue_full")
		cs.mu.Unlock()
		s.releaseReservedBytes(lineBytes)
		cs.signalStop()
		s.deactivate(id)
		return false
	}
	select {
	case cs.queue <- line:
		cs.queuedBytes += lineBytes
		omissionReason := ""
		if event.RawFrameOmitted != "" {
			omissionReason = appendReason(omissionReason, "raw_frame_omitted")
		}
		if event.RawBodyOmitted != "" {
			omissionReason = appendReason(omissionReason, "raw_body_omitted")
		}
		if omissionReason != "" {
			if leased {
				// A producer can still append the matching HTTP request/response
				// event. It marks the session incomplete when the transaction closes.
				cs.mu.Unlock()
				return true
			}
			// Keep the diagnostic event itself, then stop acceptance and let the
			// writer drain it alongside earlier events. Decoded PayloadOmitted is
			// intentionally not a reason for an incomplete capture.
			cs.stopLocked(CaptureStatusIncomplete, omissionReason)
			cs.mu.Unlock()
			cs.signalStop()
			s.deactivate(id)
			return true
		}
		cs.mu.Unlock()
		return true
	default:
		cs.stopLocked(CaptureStatusIncomplete, "queue_full")
		cs.mu.Unlock()
		s.releaseReservedBytes(lineBytes)
		cs.signalStop()
		s.deactivate(id)
		return false
	}
}

// ReadPage reads JSONL events by zero-based event offset. The page size is
// bounded to prevent one management request from loading an unbounded file.
func (s *CaptureStore) ReadPage(id string, offset, limit int) ([]Event, error) {
	if offset < 0 || limit < 1 || limit > maxCapturePageSize {
		return nil, fmt.Errorf("offset must be nonnegative and limit must be between 1 and %d", maxCapturePageSize)
	}
	cs, err := s.session(id)
	if err != nil {
		return nil, err
	}
	dataPath, _, err := s.paths(id)
	if err != nil {
		return nil, err
	}
	cs.mu.Lock()
	byteLimit := cs.meta.Bytes
	cs.mu.Unlock()
	f, err := openRegularCaptureFile(dataPath, os.O_RDONLY, 0)
	if err != nil {
		return nil, fmt.Errorf("open capture data: %w", err)
	}
	defer f.Close()

	reader := bufio.NewReader(io.NewSectionReader(f, 0, byteLimit))
	items := make([]Event, 0, limit)
	var index int
	var pageBytes int
	for index < offset || len(items) < limit {
		line, readErr := readCaptureLine(reader, maxCapturePageBytes)
		if errors.Is(readErr, ErrCaptureLineTooLarge) {
			return nil, fmt.Errorf("capture event at offset %d exceeds the %d-byte page limit; use full JSONL export", index, maxCapturePageBytes)
		}
		if len(line) == 0 && errors.Is(readErr, io.EOF) {
			break
		}
		if readErr != nil && !errors.Is(readErr, io.EOF) {
			return nil, fmt.Errorf("read capture data: %w", readErr)
		}
		if len(line) == 0 || line[len(line)-1] != '\n' {
			// A process crash or concurrent failed write can leave a partial last
			// line. It is not a complete event and is excluded from page results.
			break
		}
		if index >= offset {
			if pageBytes+len(line) > maxCapturePageBytes {
				break
			}
			var event Event
			if err = json.Unmarshal(bytes.TrimSpace(line), &event); err != nil {
				return nil, fmt.Errorf("decode capture event %d: %w", index, err)
			}
			items = append(items, event)
			pageBytes += len(line)
		}
		index++
		if errors.Is(readErr, io.EOF) {
			break
		}
	}
	return items, nil
}

// ListSessions returns persisted session metadata, newest first.
func (s *CaptureStore) ListSessions() []CaptureMetadata {
	if s == nil {
		return nil
	}
	s.mu.RLock()
	items := make([]CaptureMetadata, 0, len(s.sessions))
	for _, cs := range s.sessions {
		items = append(items, cs.snapshot())
	}
	s.mu.RUnlock()
	sort.Slice(items, func(i, j int) bool {
		if items[i].StartedAt.Equal(items[j].StartedAt) {
			return items[i].ID > items[j].ID
		}
		return items[i].StartedAt.After(items[j].StartedAt)
	})
	return items
}

// ExportSession streams a snapshot of the session's complete JSONL bytes to w.
// The returned count is the number of bytes copied.
func (s *CaptureStore) ExportSession(id string, w io.Writer) (int64, error) {
	if w == nil {
		return 0, errors.New("export writer is nil")
	}
	cs, err := s.session(id)
	if err != nil {
		return 0, err
	}
	dataPath, _, err := s.paths(id)
	if err != nil {
		return 0, err
	}
	cs.mu.Lock()
	byteLimit := cs.meta.Bytes
	cs.mu.Unlock()
	f, err := openRegularCaptureFile(dataPath, os.O_RDONLY, 0)
	if err != nil {
		return 0, fmt.Errorf("open capture data: %w", err)
	}
	defer f.Close()
	n, err := io.CopyN(w, f, byteLimit)
	if errors.Is(err, io.EOF) && n == byteLimit {
		return n, nil
	}
	if err != nil {
		return n, fmt.Errorf("stream capture data: %w", err)
	}
	return n, nil
}

// Close stops an accepting session, drains its queue and waits for all writers.
func (s *CaptureStore) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.activeID = ""
	all := make([]*captureSession, 0, len(s.sessions))
	for _, cs := range s.sessions {
		all = append(all, cs)
	}
	s.mu.Unlock()
	for _, cs := range all {
		cs.requestStop(CaptureStatusStopped, "")
	}
	for _, cs := range all {
		<-cs.done
	}
	s.mu.Lock()
	lockFile := s.lockFile
	s.lockFile = nil
	s.mu.Unlock()
	if lockFile != nil {
		return unlockCaptureDirectory(lockFile)
	}
	return nil
}

func (s *CaptureStore) session(id string) (*captureSession, error) {
	if s == nil {
		return nil, errors.New("capture store is nil")
	}
	if !validCaptureID(id) {
		return nil, ErrInvalidCapture
	}
	s.mu.RLock()
	cs := s.sessions[id]
	s.mu.RUnlock()
	if cs == nil {
		return nil, ErrCaptureNotFound
	}
	return cs, nil
}

func (s *CaptureStore) paths(id string) (string, string, error) {
	if !validCaptureID(id) {
		return "", "", ErrInvalidCapture
	}
	return filepath.Join(s.dir, id+".jsonl"), filepath.Join(s.dir, id+".meta.jsonl"), nil
}

func (s *CaptureStore) deactivate(id string) {
	s.mu.Lock()
	if s.activeID == id {
		s.activeID = ""
	}
	s.mu.Unlock()
}

func (s *CaptureStore) availableLocked() int64 {
	available := s.maxTotalBytes - s.usedBytes - s.reservedBytes
	if available < 0 {
		return 0
	}
	return available
}

// reserveBytes is called without a session lock. Keeping quota reservations
// under the store lock means no session lock is ever nested inside this path.
func (s *CaptureStore) reserveBytes(bytes int64, existingProducer bool) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed && !existingProducer {
		return ErrCaptureClosed
	}
	if bytes < 0 || bytes > s.availableLocked() {
		return ErrCaptureStorageFull
	}
	s.reservedBytes += bytes
	return nil
}

func (s *CaptureStore) releaseReservedBytes(bytes int64) {
	s.adjustStorage(bytes, 0)
}

func (s *CaptureStore) commitReservedBytes(bytes int64) {
	s.adjustStorage(bytes, bytes)
}

// adjustStorage releases reservations and adjusts persisted bytes as one
// atomic quota update. usedDelta is normally the successful line length; after
// a failed truncate it reconciles to the physical size that remains on disk.
func (s *CaptureStore) adjustStorage(releaseReserved, usedDelta int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if releaseReserved >= s.reservedBytes {
		s.reservedBytes = 0
	} else if releaseReserved > 0 {
		s.reservedBytes -= releaseReserved
	}
	if usedDelta > 0 {
		s.usedBytes += usedDelta
	} else if usedDelta < 0 {
		removedBytes := -usedDelta
		if removedBytes >= s.usedBytes {
			s.usedBytes = 0
		} else {
			s.usedBytes -= removedBytes
		}
	}
}

func (s *CaptureStore) recoverSessions() error {
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		return fmt.Errorf("read capture directory: %w", err)
	}
	seen := make(map[string]struct{})
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".meta.jsonl") || entry.IsDir() {
			continue
		}
		id := strings.TrimSuffix(name, ".meta.jsonl")
		if !validCaptureID(id) {
			continue
		}
		metaPath := filepath.Join(s.dir, name)
		meta, readErr := readLatestMetadata(metaPath, id)
		if readErr != nil {
			quarantinePath := metaPath + ".corrupt-" + time.Now().UTC().Format("20060102T150405.000000000")
			if err = os.Rename(metaPath, quarantinePath); err != nil {
				return fmt.Errorf("quarantine corrupt capture metadata %s: %w (original error: %v)", id, err, readErr)
			}
			continue
		}
		originalMeta := cloneCaptureMetadata(meta)
		dataPath, _, pathErr := s.paths(id)
		if pathErr != nil {
			return pathErr
		}
		count, size, issue, inspectErr := inspectJSONL(dataPath, meta.MaxBytes)
		diskBytes := size
		if inspectErr != nil {
			meta.Status = CaptureStatusIncomplete
			meta.IncompleteReason = "capture_file_unavailable"
			meta.Bytes, meta.EventCount = 0, 0
			diskBytes = captureDataFileSize(dataPath)
		} else {
			meta.Bytes, meta.EventCount = size, count
			if issue != "" {
				meta.Status = CaptureStatusIncomplete
				meta.IncompleteReason = issue
			}
		}
		if meta.Status == CaptureStatusRecording || meta.Status == CaptureStatusStopping {
			meta.Status = CaptureStatusIncomplete
			meta.IncompleteReason = appendReason(meta.IncompleteReason, "process_restart")
		}
		if meta.Status != CaptureStatusStopped && meta.Status != CaptureStatusIncomplete {
			meta.Status = CaptureStatusIncomplete
			meta.IncompleteReason = appendReason(meta.IncompleteReason, "invalid_metadata_status")
		}
		if meta.Status == CaptureStatusIncomplete && meta.EndedAt == nil {
			now := time.Now().UTC()
			meta.EndedAt = &now
		}
		// Append a terminal snapshot when recovering an interrupted recording.
		if !sameCaptureMetadata(originalMeta, meta) {
			if err = appendMetadataFile(metaPath, meta); err != nil {
				return fmt.Errorf("persist recovered capture metadata %s: %w", id, err)
			}
		}
		cs := recoveredSession(meta)
		s.sessions[id] = cs
		s.usedBytes += diskBytes
		seen[id] = struct{}{}
	}

	// A data file without metadata may still contain useful complete records.
	// Surface it as incomplete instead of silently hiding or discarding it.
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".jsonl") || strings.HasSuffix(name, ".meta.jsonl") || entry.IsDir() {
			continue
		}
		id := strings.TrimSuffix(name, ".jsonl")
		if !validCaptureID(id) {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		dataPath, metaPath, pathErr := s.paths(id)
		if pathErr != nil {
			return pathErr
		}
		count, size, issue, inspectErr := inspectJSONL(dataPath, s.maxSessionBytes)
		diskBytes := size
		meta := CaptureMetadata{
			ID: id, Status: CaptureStatusIncomplete, StartedAt: time.Now().UTC(),
			MaxBytes: s.maxSessionBytes, IncompleteReason: "metadata_missing",
		}
		if inspectErr == nil {
			meta.Bytes, meta.EventCount = size, count
			meta.IncompleteReason = appendReason(meta.IncompleteReason, issue)
		} else {
			meta.IncompleteReason = appendReason(meta.IncompleteReason, "capture_file_unavailable")
			diskBytes = captureDataFileSize(dataPath)
		}
		now := time.Now().UTC()
		meta.EndedAt = &now
		if err = createMetadataFile(metaPath, meta); err != nil {
			return fmt.Errorf("write recovered capture metadata %s: %w", id, err)
		}
		s.sessions[id] = recoveredSession(meta)
		s.usedBytes += diskBytes
	}
	return nil
}

func captureDataFileSize(path string) int64 {
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() {
		return 0
	}
	return info.Size()
}

func openRegularCaptureFile(path string, flag int, perm os.FileMode) (*os.File, error) {
	before, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !before.Mode().IsRegular() {
		return nil, errors.New("capture path is not a regular file")
	}
	f, err := os.OpenFile(path, flag, perm)
	if err != nil {
		return nil, err
	}
	after, err := f.Stat()
	if err != nil {
		_ = f.Close()
		return nil, err
	}
	if !after.Mode().IsRegular() || !os.SameFile(before, after) {
		_ = f.Close()
		return nil, errors.New("capture path changed while opening")
	}
	if err = f.Chmod(0600); err != nil {
		_ = f.Close()
		return nil, fmt.Errorf("restrict capture file permissions: %w", err)
	}
	return f, nil
}

func readCaptureLine(reader *bufio.Reader, maxBytes int) ([]byte, error) {
	if maxBytes <= 0 {
		return nil, errors.New("capture line read limit must be positive")
	}
	line := make([]byte, 0, min(maxBytes, 4096))
	for {
		part, err := reader.ReadSlice('\n')
		if len(part) > maxBytes-len(line) {
			return nil, ErrCaptureLineTooLarge
		}
		line = append(line, part...)
		if errors.Is(err, bufio.ErrBufferFull) {
			continue
		}
		return line, err
	}
}

func openOrCreateCaptureLock(path string) (*os.File, error) {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_RDWR, 0600)
	if err == nil {
		return file, nil
	}
	if !errors.Is(err, os.ErrExist) {
		return nil, err
	}
	return openRegularCaptureFile(path, os.O_RDWR, 0600)
}

func recoveredSession(meta CaptureMetadata) *captureSession {
	done := make(chan struct{})
	close(done)
	return &captureSession{meta: cloneCaptureMetadata(meta), done: done, producersDone: closedSignal()}
}

func closedSignal() chan struct{} {
	ch := make(chan struct{})
	close(ch)
	return ch
}

func (cs *captureSession) isAccepting() bool {
	cs.mu.Lock()
	defer cs.mu.Unlock()
	return cs.accepting
}

func (cs *captureSession) canAppend(leased bool) bool {
	cs.mu.Lock()
	defer cs.mu.Unlock()
	return cs.canAppendLocked(leased)
}

func (cs *captureSession) canAppendLocked(leased bool) bool {
	if cs.accepting {
		return true
	}
	return leased && cs.stopStatus == CaptureStatusStopped && cs.producers > 0
}

func (cs *captureSession) snapshot() CaptureMetadata {
	cs.mu.Lock()
	defer cs.mu.Unlock()
	return cloneCaptureMetadata(cs.meta)
}

func (cs *captureSession) requestStop(status, reason string) bool {
	cs.mu.Lock()
	started := cs.accepting
	if started {
		cs.stopLocked(status, reason)
	}
	idle := cs.producersDone
	drainProducers := cs.stopStatus == CaptureStatusStopped
	cs.mu.Unlock()
	if drainProducers {
		<-idle
	}
	cs.signalStop()
	return started
}

func (cs *captureSession) markIncompleteBeforeDrain(reason string) {
	cs.mu.Lock()
	var deactivateID string
	switch {
	case cs.accepting:
		deactivateID = cs.meta.ID
		cs.stopLocked(CaptureStatusIncomplete, reason)
	case cs.stopStatus == CaptureStatusStopped && cs.meta.Status == CaptureStatusStopping:
		cs.stopStatus = CaptureStatusIncomplete
		cs.stopReason = appendReason(cs.stopReason, reason)
	}
	cs.mu.Unlock()
	if deactivateID != "" {
		cs.store.deactivate(deactivateID)
		cs.signalStop()
	}
}

func (cs *captureSession) fail(reason string) {
	cs.mu.Lock()
	if !cs.accepting {
		cs.mu.Unlock()
		return
	}
	id := cs.meta.ID
	cs.stopLocked(CaptureStatusIncomplete, reason)
	cs.mu.Unlock()
	cs.store.deactivate(id)
	cs.signalStop()
}

func (cs *captureSession) stopLocked(status, reason string) {
	cs.accepting = false
	cs.stopStatus = status
	if reason != "" {
		cs.stopReason = appendReason(cs.stopReason, reason)
	}
	cs.meta.Status = CaptureStatusStopping
	if cs.meta.EndedAt == nil {
		now := time.Now().UTC()
		cs.meta.EndedAt = &now
	}
}

func (cs *captureSession) signalStop() {
	select {
	case cs.stop <- struct{}{}:
	default:
	}
}

func (cs *captureSession) run() {
	defer close(cs.done)
	defer cs.store.deactivate(cs.meta.ID)
	for {
		select {
		case line := <-cs.queue:
			if !cs.writeLine(line) {
				cs.finish()
				return
			}
		case <-cs.stop:
			for {
				select {
				case line := <-cs.queue:
					if !cs.writeLine(line) {
						cs.finish()
						return
					}
				default:
					cs.finish()
					return
				}
			}
		}
	}
}

func (cs *captureSession) writeLine(line []byte) bool {
	cs.mu.Lock()
	if cs.file == nil {
		cs.mu.Unlock()
		cs.discardQueued("capture_file_unavailable", 0)
		return false
	}
	if cs.meta.Bytes+cs.queuedBytes > cs.meta.MaxBytes {
		cs.mu.Unlock()
		cs.discardQueued("max_bytes_reached", 0)
		return false
	}
	f := cs.file
	persistedBytes := cs.meta.Bytes
	cs.mu.Unlock()
	// Keep the line reserved in queuedBytes while the disk write is in flight.
	// Append can then make a bounded decision without taking a lock held over I/O.
	if err := writeAll(f, line); err != nil {
		var extraPhysicalBytes int64
		if truncateErr := f.Truncate(persistedBytes); truncateErr == nil {
			_, _ = f.Seek(persistedBytes, io.SeekStart)
		} else if stat, statErr := f.Stat(); statErr == nil {
			// The reservation covers this attempted line. If the partial bytes
			// cannot be removed, reconcile usedBytes to the physical size before
			// releasing the rest of the queue reservation.
			extraPhysicalBytes = stat.Size() - persistedBytes
		}
		cs.discardQueued("disk_write_failed", extraPhysicalBytes)
		return false
	}
	cs.mu.Lock()
	cs.meta.Bytes += int64(len(line))
	cs.meta.EventCount++
	cs.queuedBytes -= int64(len(line))
	if cs.queuedBytes < 0 {
		cs.queuedBytes = 0
	}
	cs.mu.Unlock()
	cs.store.commitReservedBytes(int64(len(line)))
	return true
}

// discardQueued is used after a writer failure. It marks the session
// incomplete, clears the byte reservation for the current in-flight line and
// all lines still buffered, and drains their memory from the channel.
func (cs *captureSession) discardQueued(reason string, extraPhysicalBytes int64) {
	cs.mu.Lock()
	cs.stopLocked(CaptureStatusIncomplete, reason)
	reservedBytes := cs.queuedBytes
	cs.queuedBytes = 0
	id := cs.meta.ID
	cs.mu.Unlock()
	for {
		select {
		case <-cs.queue:
		default:
			cs.store.adjustStorage(reservedBytes, extraPhysicalBytes)
			cs.store.deactivate(id)
			return
		}
	}
}

func (cs *captureSession) finish() {
	cs.metadataMu.Lock()
	defer cs.metadataMu.Unlock()
	cs.mu.Lock()
	if cs.stopStatus == "" {
		cs.stopStatus = CaptureStatusIncomplete
		cs.stopReason = appendReason(cs.stopReason, "writer_stopped_unexpectedly")
	}
	f := cs.file
	cs.file = nil
	cs.mu.Unlock()
	if f != nil {
		if err := f.Sync(); err != nil {
			cs.mu.Lock()
			cs.stopStatus = CaptureStatusIncomplete
			cs.stopReason = appendReason(cs.stopReason, "disk_sync_failed")
			cs.mu.Unlock()
		}
		if err := f.Close(); err != nil {
			cs.mu.Lock()
			cs.stopStatus = CaptureStatusIncomplete
			cs.stopReason = appendReason(cs.stopReason, "disk_close_failed")
			cs.mu.Unlock()
		}
	}
	cs.mu.Lock()
	cs.meta.Status = cs.stopStatus
	cs.meta.IncompleteReason = ""
	if cs.stopStatus == CaptureStatusIncomplete {
		cs.meta.IncompleteReason = cs.stopReason
	}
	if cs.meta.EndedAt == nil {
		now := time.Now().UTC()
		cs.meta.EndedAt = &now
	}
	meta := cloneCaptureMetadata(cs.meta)
	cs.mu.Unlock()

	_, metaPath, err := cs.store.paths(meta.ID)
	if err == nil {
		err = appendMetadataFile(metaPath, meta)
	}
	if err != nil {
		cs.mu.Lock()
		cs.meta.Status = CaptureStatusIncomplete
		cs.meta.IncompleteReason = appendReason(cs.meta.IncompleteReason, "metadata_write_failed")
		cs.mu.Unlock()
	}
}

func (cs *captureSession) noteLateEvent() {
	cs.metadataMu.Lock()
	defer cs.metadataMu.Unlock()
	cs.mu.Lock()
	if cs.accepting {
		cs.mu.Unlock()
		return
	}
	if cs.meta.Status == CaptureStatusStopping {
		cs.stopStatus = CaptureStatusIncomplete
		cs.stopReason = appendReason(cs.stopReason, "event_completed_after_stop")
		cs.mu.Unlock()
		return
	}
	if cs.meta.Status != CaptureStatusStopped {
		cs.mu.Unlock()
		return
	}
	cs.meta.Status = CaptureStatusIncomplete
	cs.meta.IncompleteReason = appendReason(cs.meta.IncompleteReason, "event_completed_after_stop")
	meta := cloneCaptureMetadata(cs.meta)
	cs.mu.Unlock()
	_, metaPath, err := cs.store.paths(meta.ID)
	if err == nil {
		err = appendMetadataFile(metaPath, meta)
	}
	if err != nil {
		cs.mu.Lock()
		cs.meta.IncompleteReason = appendReason(cs.meta.IncompleteReason, "metadata_write_failed")
		cs.mu.Unlock()
	}
}

func newCaptureID() (string, error) {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(raw[:]), nil
}

func validCaptureID(id string) bool {
	if len(id) != 32 {
		return false
	}
	for _, r := range id {
		if !(r >= '0' && r <= '9' || r >= 'a' && r <= 'f') {
			return false
		}
	}
	return true
}

func cloneCaptureMetadata(meta CaptureMetadata) CaptureMetadata {
	if meta.EndedAt != nil {
		endedAt := *meta.EndedAt
		meta.EndedAt = &endedAt
	}
	return meta
}

func createMetadataFile(path string, meta CaptureMetadata) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	line, marshalErr := marshalMetadataLine(meta)
	if marshalErr == nil {
		marshalErr = writeAll(f, line)
	}
	if marshalErr == nil {
		marshalErr = f.Sync()
	}
	closeErr := f.Close()
	if marshalErr != nil {
		_ = os.Remove(path)
		return marshalErr
	}
	return closeErr
}

func appendMetadataFile(path string, meta CaptureMetadata) error {
	f, err := openRegularCaptureFile(path, os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	line, err := marshalMetadataLine(meta)
	if err == nil {
		err = writeAll(f, line)
	}
	if err == nil {
		err = f.Sync()
	}
	closeErr := f.Close()
	if err != nil {
		return err
	}
	return closeErr
}

func marshalMetadataLine(meta CaptureMetadata) ([]byte, error) {
	line, err := json.Marshal(meta)
	if err != nil {
		return nil, err
	}
	return append(line, '\n'), nil
}

func readLatestMetadata(path, id string) (CaptureMetadata, error) {
	f, err := openRegularCaptureFile(path, os.O_RDWR, 0600)
	if err != nil {
		return CaptureMetadata{}, err
	}
	defer f.Close()
	reader := bufio.NewReader(f)
	var latest CaptureMetadata
	found := false
	var validBytes int64
	for {
		line, readErr := readCaptureLine(reader, maxCaptureMetadataLine)
		if errors.Is(readErr, ErrCaptureLineTooLarge) {
			return CaptureMetadata{}, readErr
		}
		if len(line) == 0 && errors.Is(readErr, io.EOF) {
			break
		}
		if errors.Is(readErr, io.EOF) && len(line) > 0 {
			// An interrupted append cannot supersede the previous complete record.
			if err = f.Truncate(validBytes); err != nil {
				return CaptureMetadata{}, err
			}
			if err = f.Sync(); err != nil {
				return CaptureMetadata{}, err
			}
			break
		}
		if readErr != nil && !errors.Is(readErr, io.EOF) {
			return CaptureMetadata{}, readErr
		}
		var current CaptureMetadata
		if err = json.Unmarshal(bytes.TrimSpace(line), &current); err != nil {
			return CaptureMetadata{}, fmt.Errorf("invalid metadata line: %w", err)
		}
		if current.ID != id || current.MaxBytes <= 0 {
			return CaptureMetadata{}, errors.New("metadata does not match its filename or has no byte limit")
		}
		latest, found = current, true
		validBytes += int64(len(line))
		if errors.Is(readErr, io.EOF) {
			break
		}
	}
	if !found {
		return CaptureMetadata{}, errors.New("metadata has no complete record")
	}
	return latest, nil
}

func sameCaptureMetadata(a, b CaptureMetadata) bool {
	if a.ID != b.ID || a.Status != b.Status || !a.StartedAt.Equal(b.StartedAt) ||
		a.MaxBytes != b.MaxBytes || a.Bytes != b.Bytes || a.EventCount != b.EventCount ||
		a.IncompleteReason != b.IncompleteReason {
		return false
	}
	if a.EndedAt == nil || b.EndedAt == nil {
		return a.EndedAt == nil && b.EndedAt == nil
	}
	return a.EndedAt.Equal(*b.EndedAt)
}

func inspectJSONL(path string, maxBytes int64) (eventCount, validBytes int64, issue string, err error) {
	f, err := openRegularCaptureFile(path, os.O_RDWR, 0600)
	if err != nil {
		return 0, 0, "", err
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
	}()
	reader := bufio.NewReader(f)
	var offset int64
	for {
		line, readErr := readCaptureLine(reader, defaultCaptureQueueBytes)
		if errors.Is(readErr, ErrCaptureLineTooLarge) {
			issue = "capture_line_over_limit"
			break
		}
		if len(line) == 0 && errors.Is(readErr, io.EOF) {
			break
		}
		if errors.Is(readErr, io.EOF) {
			issue = "trailing_partial_line"
			break
		}
		if readErr != nil {
			return eventCount, offset, "", readErr
		}
		if offset+int64(len(line)) > maxBytes {
			issue = "capture_file_over_limit"
			break
		}
		var event Event
		if err = json.Unmarshal(bytes.TrimSpace(line), &event); err != nil {
			issue = "invalid_jsonl_event"
			break
		}
		offset += int64(len(line))
		eventCount++
	}
	stat, statErr := f.Stat()
	if statErr != nil {
		return eventCount, offset, issue, statErr
	}
	if offset < stat.Size() {
		if truncateErr := f.Truncate(offset); truncateErr != nil {
			return eventCount, offset, issue, truncateErr
		}
		if syncErr := f.Sync(); syncErr != nil {
			return eventCount, offset, issue, syncErr
		}
	}
	return eventCount, offset, issue, nil
}

func writeAll(w io.Writer, data []byte) error {
	for len(data) > 0 {
		n, err := w.Write(data)
		if err != nil {
			return err
		}
		if n == 0 {
			return io.ErrShortWrite
		}
		data = data[n:]
	}
	return nil
}

func appendReason(existing, next string) string {
	if next == "" {
		return existing
	}
	if existing == "" {
		return next
	}
	for _, part := range strings.Split(existing, ";") {
		if part == next {
			return existing
		}
	}
	return existing + ";" + next
}
